name: needs-workflow
on:
    push:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "job 1 is done!"

    job2:
        needs: [job1]
        runs-on: ubuntu-latest
        steps:
            - name: step2
              run: echo "job 2 is done!"

    job3:
        runs-on: ubuntu-latest
        steps:
            - name: step3
              run: |
                echo "job3 failed"
                exit 1

    job4:
        needs: [job3]
        runs-on: ubuntu-latest
        steps:
            - name: step4
              run: echo "job4 is done!"
