name: artifact-workflow
on:
    push

jobs:
    upload-artifact-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo-step
              run: echo "Hello, World!" -> hello.txt
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-test
                path: ./hello.txt

    download-artifact-job:
        runs-on: ubuntu-latest
        needs: [upload-artifact-job]
        steps:
            - name: download-artifact
              uses: actions/download-artifact@v4
              with:
                name: artifact-test
                path: ./
            - name: check
              run: cat ./hello.txt