name: output-workflow
on:
    push

jobs:
    create-output-job:
        runs-on: ubuntu-latest
        outputs:
            test: ${{ steps.check-output.outputs.test }}
        steps:
            - name: echo-output
              id : check-output
              run: |
                echo "test=hello" >> $GITHUB_OUTPUT
            - name: check-output
              run: |
                echo ${{steps.check-output.outputs.test}}

    get-output-job:
        runs-on: ubuntu-latest
        needs: [create-output-job]
        steps:
            - name: get-output
              run: |
                echo ${{needs.create-output-job.outputs.test}}