name: branch-filter-workflow
on:
    push:
        branches: ['main']

jobs:
    branch-filter-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello, World!!!"
            - name: step2
              run: echo "github action!!!!!!!"




