name: environment-workflow
on: push

jobs:
    get-environment:
        runs-on: ubuntu-latest
        steps:
        - name: check-environment
          run: |
           echo "LEVEL ${{ vars.LEVEL }}"
           echo "KEY ${{secrets.KEY}}"
