name: if-1-workflow
on:
    push:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: get-event-name
              run: echo "EVENT_NAME ${{ github.event_name }}"

    job2:
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: get-event-name
              run: echo "EVENT_NAME ${{ github.event_name }}"
        
    job3:
        runs-on: ubuntu-latest
        steps:
            - name: get-event-name
              if: github.event_name == 'push'
              run: echo 'PUSH'
            - name: get-event-name
              if: github.event_name != 'push'
              run: echo 'dispatched'

    job4:
        runs-on: ubuntu-latest
        steps:
            - name: exit 1
              run: exit 1
            - name: echo
              run: echo hello
    
    job5:
        runs-on: ubuntu-latest
        if: always()
        needs: [job4]
        steps:
            - name: echo
              run: echo hello




