name: issue-notify-workflow
on:
    issues:
        types: [opened]

jobs:
    get-keyword-job:
        runs-on: ubuntu-latest
        outputs:
            level: ${{ steps.get-keyword.outputs.level }}
        steps:
            - name: checkout github 
              uses: actions/checkout@v4
            - name: get keyword
              id : get-keyword
              run: |
                echo level=Undefined >> $GITHUB_OUTPUT
                keywords=$(cat keyword-list.txt)
                for keyword in $keywords; do
                    if [[ "${{ github.event.issue.title }}" =~ $keyword ]]; then
                        echo level=$keyword >> $GITHUB_OUTPUT
                        break
                    fi
                done
            - name: get output
              run: |
                echo ${{steps.get-keyword.outputs.level}}
