name: issue-notify-workflow
on:
    issues:
        types: [opened]

jobs:
    get-keyword:
        runs-on: ubuntu-latest
        outputs:
            level: ${{ steps.get-keyword.outputs.level }}
        steps:
            - name: checkout github 
              uses: actions/checkout@v4
            - name: get keyword
              id : get-keyword
              run: |
                echo level=Undefined >> $GITHUB_OUTPUT
                keywords=$(cat keyword-list.txt)
                for keyword in $keywords; do
                    if [[ "${{ github.event.issue.title }}" =~ $keyword ]]; then
                        echo level=$keyword >> $GITHUB_OUTPUT
                        break
                    fi
                done
            - name: get output
              run: |
                echo ${{steps.get-keyword.outputs.level}}
                
    slack-notify-job:
        needs: [get-keyword]
        if: needs.get-keyword.outputs.level != 'Undefined'
        environment: ${{ needs.get-keyword.outputs.level }}
        runs-on: ubuntu-latest
        steps:
            - name: notify-slack
              if: always()
              uses: slackapi/slack-github-action@v1.24.0
              with:
                payload: |
                  {
                    "attachments": [{
                      "pretext": "issue alert message",
                      "color": "28a745",
                      "fields": [{
                        "title": "Level ${{needs.get-keyword.outputs.level}}}",
                        "value": "issue url : ${{github.event.issue.html_url}}",
                        "short": true
                      }]
                    }]
                  }
              env: 
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
