name: multiple-event-workflow
on:
    push:
    issues:
        types: [opened]
    workflow_dispatch:

jobs:
    multiple-event-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello, World!!!"
            - name: step2
              run: echo "github action!!!!!!!"
            - name: step3
              run: |
                echo "안녕하세요!"
                echo "저는 리벨리온 System Software DevOps 팀의"
                echo "이대연입니디ㅏ."