name: multiple-event-workflow

on:
  push:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  multiple-event-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 (공통 실행)
        run: echo "Hello, World!!!"

      - name: step2 (공통 실행)
        run: echo "github action!!!!!!!"

      - name: step3 (이슈일 때만 실행)
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "안녕하세요!"
          echo "저는 리벨리온 System Software DevOps 팀의"
          echo "이대연입니디ㅏ."
