name: path-filter-workflow
on:
    push:
        paths:
            - '.github/workflows/part1/*'
            - '!.github/workflows/part2/push.yaml'

jobs:
    path-filter-job:
        runs-on: ubuntu-latest
        steps:
            - name: echo path
              run: echo ${{ github.event.head_commit.modified }}