name: pull_request-workflow
on: 
    pull_request:
        types: [opened]

jobs:
    pull_request-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello, World!"
            - name: step2
              run: echo "Bye, World!"
            - name: step3
              run: |
                echo "안녕하세요!"