name: timeout-workflow
on: push

jobs:
    timeout-job:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: loop-step
              run: |
                count=0
                while true; do
                    echo "seconds : $count"
                    count=$((count+1))
                    sleep 1
                done
            - name : echo-step
              run: echo "job is done