name: workflow-dispatch-workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: "set-name"
                required: true
                default: "github-actions"
                type: string
            environment:
                description: "set-environment"
                required: true
                default: "main"
                type: choice
                options:
                    - dev
                    - prod
                    - qa

jobs:
    workflow-dispatch-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello, World!!!"
            - name: step2
              run: echo "github action!!!!!!!"
            - name: echo inputs
              run: |
                echo ${{ inputs.name }}
                echo ${{ inputs.environment }}



